apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-golem-orchestrator-default
  namespace: golem-providers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-golem-orchestrator-default
subjects:
  - kind: ServiceAccount
    name: prod-golem-orchestrator-default
    namespace: golem-infrastructure
