apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-secret-store
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: op-token
            namespace: onepassword
      connectHost: http://onepassword-connect.onepassword.svc.cluster.local:8080
      vaults:
        "Connect - Golem Integration": 1
