apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: kube-state-metrics
  name: kube-state-metrics
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  info:
    - name: SaladTechnologies/salad-golem-integration
      value: https://github.com/SaladTechnologies/salad-golem-integration/
  project: default
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "6.4.2"
    helm:
      releaseName: kube-state-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
