apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10000"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: external-secrets
  name: external-secrets
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: "1.1.1"
    helm:
      releaseName: external-secrets
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
