apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: onepassword-secret-store
  name: onepassword-secret-store
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: onepassword
  project: default
  source:
    path: cluster/apps/onepassword-secret-store
    repoURL: https://github.com/SaladTechnologies/salad-golem-integration.git
    targetRevision: HEAD
